/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appenglish;

import javax.swing.GroupLayout;
import javax.swing.*;
import java.awt.event.*;
import java.util.*;
import java.io.*;
import java.sql.*;
import com.microsoft.sqlserver.jdbc.*;
import java.awt.Color;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.image.BufferedImage;
import java.util.Date;
import java.text.*;
import java.awt.Color;
import javax.swing.GroupLayout;
import javax.swing.*;
import java.awt.event.*;
import java.util.*;
import java.io.*;
import java.sql.*;
import com.microsoft.sqlserver.jdbc.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.awt.image.BufferedImage;
import java.util.Date;
import java.text.*;
/**
 *
 * @author Bui
 */
public class ChangeWord extends javax.swing.JFrame {

    public static String pathToImage = "";
    public static String connectionUrl = "jdbc:sqlserver://localhost:1433;" +  
     "databaseName=AppEnglish;integratedSecurity=true;"; 
    public static Connection connection = null;  
    public static Statement statement = null;   
    public static ResultSet resultSet = null;  
    public PreparedStatement prepsInsertProduct = null; 
    public ChangeWord() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        changeMeaningRadioButton = new javax.swing.JRadioButton();
        changeSubjectRadioButton = new javax.swing.JRadioButton();
        ChangeImageRadioButton = new javax.swing.JRadioButton();
        notifyLabel = new javax.swing.JLabel();
        meaningTextField = new javax.swing.JTextField();
        confirmChangeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        chooseImageButton = new javax.swing.JButton();
        subjectComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập từ bạn cần thay đổi");

        searchButton.setText("TÌm kiếm");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Chọn nội dung bạn muốn thay đổi ");
        jLabel2.setVisible(false);

        changeMeaningRadioButton.setSelected(true);
        changeMeaningRadioButton.setText("Nghĩa của từ");
        changeMeaningRadioButton.setVisible(false);
        changeMeaningRadioButton.setSelected(false);
        changeMeaningRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                changeMeaningRadioButtonStateChanged(evt);
            }
        });
        changeMeaningRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeMeaningRadioButtonMouseClicked(evt);
            }
        });

        changeSubjectRadioButton.setSelected(true);
        changeSubjectRadioButton.setText("Chủ đề");
        changeSubjectRadioButton.setVisible(false);
        changeSubjectRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSubjectRadioButtonActionPerformed(evt);
            }
        });
        changeSubjectRadioButton.setSelected(false);

        ChangeImageRadioButton.setText("Hình ảnh");
        ChangeImageRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangeImageRadioButtonActionPerformed(evt);
            }
        });
        ChangeImageRadioButton.setVisible(false);

        notifyLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notifyLabel.setForeground(new java.awt.Color(255, 0, 0));
        notifyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        notifyLabel.setText("Từ không tồn tại");
        notifyLabel.setVisible(false);

        meaningTextField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        meaningTextField.setVisible(false);

        confirmChangeButton.setText("Xác nhận");
        confirmChangeButton.setVisible(false);
        confirmChangeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmChangeButtonMouseClicked(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đổi thành :");
        jLabel3.setVisible(false);

        chooseImageButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        chooseImageButton.setText("Chon tệp");
        chooseImageButton.setVisible(false);
        chooseImageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chooseImageButtonMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setVisible(false);
        jLabel4.setForeground(new java.awt.Color(51, 0, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Đã thay đổi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addComponent(notifyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(changeMeaningRadioButton)
                                    .addComponent(changeSubjectRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChangeImageRadioButton))
                                .addGap(162, 162, 162)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(meaningTextField)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chooseImageButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(subjectComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(confirmChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(notifyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeMeaningRadioButton)
                    .addComponent(meaningTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeSubjectRadioButton)
                    .addComponent(subjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChangeImageRadioButton)
                    .addComponent(chooseImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(confirmChangeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ChangeImageRadioButton.setSelected(false);
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String sqlquery = "SELECT * FROM Subject";
            connection = DriverManager.getConnection(connectionUrl);
            statement = connection.createStatement();
            resultSet =  statement.executeQuery(sqlquery);
            while (resultSet.next())
            {
                subjectComboBox.addItem(resultSet.getString(1));
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        subjectComboBox.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeImageRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeImageRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeImageRadioButtonActionPerformed

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String sqlquery = "SELECT * FROM dbo.wordData WHERE word = '" + searchTextField.getText() + "'";
            connection = DriverManager.getConnection(connectionUrl);
            statement = connection.createStatement();
            resultSet =  statement.executeQuery(sqlquery);
            if(!resultSet.isBeforeFirst())
            {
                notifyLabel.setVisible(true);
                jLabel2.setVisible(false);
                changeMeaningRadioButton.setVisible(false);
                changeSubjectRadioButton.setVisible(false);
                ChangeImageRadioButton.setVisible(false);
                meaningTextField.setVisible(false);
                subjectComboBox.setVisible(false);
                chooseImageButton.setVisible(false);
                confirmChangeButton.setVisible(false);
            }
            else
            {
                notifyLabel.setVisible(false);
                jLabel2.setVisible(true);
                changeMeaningRadioButton.setVisible(true);
                changeSubjectRadioButton.setVisible(true);
                ChangeImageRadioButton.setVisible(true);
                meaningTextField.setVisible(true);
                subjectComboBox.setVisible(true);
                chooseImageButton.setVisible(true);
                confirmChangeButton.setVisible(true);
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_searchButtonMouseClicked

    private void changeSubjectRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSubjectRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_changeSubjectRadioButtonActionPerformed

    private void chooseImageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chooseImageButtonMouseClicked
        JFileChooser filechooser = new JFileChooser();
        int retval = filechooser.showOpenDialog(null);
        if(retval == JFileChooser.APPROVE_OPTION)
        {
            File imageFile =filechooser.getSelectedFile();
            pathToImage = imageFile.getAbsolutePath().replace("\\","\\\\");
        }
    }//GEN-LAST:event_chooseImageButtonMouseClicked

    private void changeMeaningRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_changeMeaningRadioButtonStateChanged
        
    }//GEN-LAST:event_changeMeaningRadioButtonStateChanged

    private void changeMeaningRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMeaningRadioButtonMouseClicked
       
    }//GEN-LAST:event_changeMeaningRadioButtonMouseClicked

    private void confirmChangeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmChangeButtonMouseClicked
        String updateSql = "UPDATE dbo.wordData SET";
        if(changeMeaningRadioButton.isSelected())
        {
            updateSql += " meaning = N'"+ meaningTextField.getText() + "'";
        }
        if(changeSubjectRadioButton.isSelected())
        {
            updateSql += ",subjectOfWord = N'"+ subjectComboBox.getItemAt(subjectComboBox.getSelectedIndex()) + "' ";
        }
        if(ChangeImageRadioButton.isSelected())
        {
            updateSql += ",imageOfWord = N'" + pathToImage + "' ";
        }
        updateSql += "WHERE word = N'" + searchTextField.getText()+"'";
//        System.out.println(updateSql);
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); 
            connection = DriverManager.getConnection(connectionUrl);  
            statement = connection.createStatement();
            prepsInsertProduct = connection.prepareStatement(  
            updateSql,  
            Statement.RETURN_GENERATED_KEYS);  
            prepsInsertProduct.execute();  

        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }    
        jLabel4.setVisible(true);
    }//GEN-LAST:event_confirmChangeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeWord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ChangeImageRadioButton;
    private javax.swing.JRadioButton changeMeaningRadioButton;
    private javax.swing.JRadioButton changeSubjectRadioButton;
    private javax.swing.JButton chooseImageButton;
    private javax.swing.JButton confirmChangeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField meaningTextField;
    private javax.swing.JLabel notifyLabel;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JComboBox<String> subjectComboBox;
    // End of variables declaration//GEN-END:variables
}
