/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appenglish;

import static appenglish.ReviewWord.imgList;
import static appenglish.ReviewWord.meaningList;
import static appenglish.ReviewWord.numOfWords;
import static appenglish.ReviewWord.wordList;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
public class HomePage extends javax.swing.JFrame implements WindowListener{

    public List<Integer> newWordEachDay = new ArrayList<Integer>();
    public List<Integer> reviewWordEachDay = new ArrayList<Integer>();
    
     public String connectionUrl = "jdbc:sqlserver://localhost:1433;" +  
     "databaseName=AppEnglish;integratedSecurity=true;"; 
    public Connection connection = null;  
    public  Statement statement = null;   
    public  ResultSet resultSet = null;  
    
    public PreparedStatement prepsInsertProduct = null; 
    
    public HomePage() 
    {
        initComponents();
        readProgressDb();
    }
    public void readProgressDb()
    {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
        Date date = new Date();
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String selectSql = "SELECT * FROM dbo.learningProgress " +
                     "WHERE activeDate = N'" + dateFormat.format(date)+"'" ;
            
            connection = DriverManager.getConnection(connectionUrl);
            statement = connection.createStatement();
            resultSet =  statement.executeQuery(selectSql);
            
            if(!resultSet.isBeforeFirst())
            {
                try
                {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver"); 
                    connection = DriverManager.getConnection(connectionUrl);  
                    statement = connection.createStatement();

                    String insertSql = "INSERT INTO dbo.learningProgress VALUES (0,0,N'" + dateFormat.format(date)+
                            "')";
                    
                    prepsInsertProduct = connection.prepareStatement(  
                    insertSql,  
                    Statement.RETURN_GENERATED_KEYS);  
                    prepsInsertProduct.execute();  
                }
                catch(Exception ex)
                {
                    ex.printStackTrace();
                }    
            }
//            else
//            {
//                    newWordEachDay.add(resultSet.getInt(1));
//                    reviewWordEachDay.add(resultSet.getInt(2));
//            }
        }       
        
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        reviewButton = new java.awt.Button();
        manageDIcButton = new java.awt.Button();
        manageWordButton = new java.awt.Button();
        testButton = new java.awt.Button();
        statisticButton = new java.awt.Button();
        label1 = new java.awt.Label();
        createButton = new javax.swing.JButton("Tạo chủ đề");
        goalButton = new javax.swing.JButton();
        learnButton = new javax.swing.JButton();
        notifyButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(500, 500));

        reviewButton.setLabel("Ôn tập");
        reviewButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reviewButtonMouseClicked(evt);
            }
        });

        manageDIcButton.setLabel("Quản lý từ điển");
        manageDIcButton.setName("Quản lý từ điển"); // NOI18N
        manageDIcButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageDIcButtonMouseClicked(evt);
            }
        });

        manageWordButton.setLabel("Quản lý từ vựng");
        manageWordButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageWordButtonMouseClicked(evt);
            }
        });

        testButton.setLabel("Kiếm tra\n");
        testButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                testButtonMouseClicked(evt);
            }
        });

        statisticButton.setLabel("Thống kê");
        statisticButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statisticButtonMouseClicked(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label1.setText("Learn English");

        createButton.setLabel("Tạo chủ đề");
        createButton.setText("Tạo chủ đề");
        createButton.setToolTipText("");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });

        goalButton.setText("Đặt muc tiêu");
        goalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goalButtonMouseClicked(evt);
            }
        });
        goalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goalButtonActionPerformed(evt);
            }
        });

        learnButton.setText("Học ");
        learnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                learnButtonMouseClicked(evt);
            }
        });

        notifyButton.setText("Thông báo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(goalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(manageWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(reviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(learnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageDIcButton, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(statisticButton, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(notifyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageDIcButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(reviewButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(testButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manageWordButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(statisticButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(goalButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(learnButton)
                    .addComponent(notifyButton))
                .addGap(78, 78, 78))
        );

        createButton.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        Create createFrame = new Create();
        createFrame.setVisible(true);
    }//GEN-LAST:event_createButtonMouseClicked

    private void reviewButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reviewButtonMouseClicked
        Review reviewFrame = new Review();
        reviewFrame.setVisible(true);
    }//GEN-LAST:event_reviewButtonMouseClicked

    private void manageDIcButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageDIcButtonMouseClicked
        ManageDictionary ManageDictionaryFrame = new ManageDictionary();
        ManageDictionaryFrame.setVisible(true);
    }//GEN-LAST:event_manageDIcButtonMouseClicked

    private void manageWordButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageWordButtonMouseClicked
        Manage manageFrame = new Manage();
        manageFrame.setVisible(true);
    }//GEN-LAST:event_manageWordButtonMouseClicked

    private void goalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goalButtonActionPerformed
        setGoal setGoalFrame = new setGoal();
        setGoalFrame.setVisible(true);
    }//GEN-LAST:event_goalButtonActionPerformed

    private void goalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goalButtonMouseClicked
        setGoal setGoalFrame = new setGoal();
        setGoalFrame.setVisible(true);
    }//GEN-LAST:event_goalButtonMouseClicked

    private void learnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learnButtonMouseClicked
  
        Learn learnFrame = new Learn();
        learnFrame.setVisible(true);  
        learnFrame.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {
               
            }

            @Override
            public void windowClosing(WindowEvent e) {
                learnFrame.windowClosing(e);
            }

            @Override
            public void windowClosed(WindowEvent e) {
                
            }

            @Override
            public void windowIconified(WindowEvent e) {
                
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
                
            }

            @Override
            public void windowActivated(WindowEvent e) {
                
            }
            @Override
            public void windowDeactivated(WindowEvent e) {
                
            }
        });
    }//GEN-LAST:event_learnButtonMouseClicked

    private void statisticButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statisticButtonMouseClicked
        Statistic statistic = new Statistic();
        String[] args = {};
        statisticButton.setVisible(false);
        try 
        {
            statistic.main(args);
        } catch (ParseException ex) 
        {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_statisticButtonMouseClicked

    private void testButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_testButtonMouseClicked
        Test testFrame = new Test();
        testFrame.setVisible(true);
    }//GEN-LAST:event_testButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton goalButton;
    private java.awt.Label label1;
    private javax.swing.JButton learnButton;
    private java.awt.Button manageDIcButton;
    private java.awt.Button manageWordButton;
    private javax.swing.JButton notifyButton;
    private java.awt.Button reviewButton;
    private java.awt.Button statisticButton;
    private java.awt.Button testButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) 
    {
       System.out.println("Opened");
    }

    @Override
    public void windowClosing(WindowEvent e) {
       System.out.println("Closing");
    }

    @Override
    public void windowClosed(WindowEvent e){
    }
   
    @Override
    public void windowIconified(WindowEvent e) 
    {
        System.out.println("windowIconified");
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
         System.out.println("windowDeiconified");
    }

    @Override
    public void windowActivated(WindowEvent e) {
        System.out.println("Activated");
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        
    }
}
