/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appenglish;

import java.awt.Color;

/**
 *
 * @author Bui
 */
public class Manage extends javax.swing.JFrame {

    /**
     * Creates new form Manage
     */
    public Manage() {
        
        initComponents();
        buttonGroup1.add(changeRadioButton);
        buttonGroup1.add(deleteRadioButton);
        buttonGroup1.add(addRadioButton);
        buttonGroup2.add(handRadioButton);
        buttonGroup2.add(excelRadioButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jToggleButton1 = new javax.swing.JToggleButton();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        handRadioButton = new javax.swing.JRadioButton("Hand");
        excelRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        addRadioButton = new javax.swing.JRadioButton();
        changeRadioButton = new javax.swing.JRadioButton();
        deleteRadioButton = new javax.swing.JRadioButton();
        notifyLabel = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        handRadioButton.setText("Hand");
        handRadioButton.setVisible(false);

        excelRadioButton.setText("Excel");
        excelRadioButton.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Click để hành động");

        confirmButton.setText("Xác nhận");
        confirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmButtonMouseClicked(evt);
            }
        });

        addRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addRadioButton.setText("Thêm từ");
        addRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRadioButtonMouseClicked(evt);
            }
        });

        changeRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        changeRadioButton.setText("Sửa từ");
        changeRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeRadioButtonMouseClicked(evt);
            }
        });

        deleteRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteRadioButton.setText("Xóa từ");
        deleteRadioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteRadioButtonMouseClicked(evt);
            }
        });

        notifyLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notifyLabel.setForeground(new java.awt.Color(255, 51, 51));
        notifyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(confirmButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(changeRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteRadioButton, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(handRadioButton)
                    .addComponent(excelRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(notifyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(addRadioButton)
                        .addGap(50, 50, 50)
                        .addComponent(changeRadioButton)
                        .addGap(57, 57, 57)
                        .addComponent(deleteRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(handRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(excelRadioButton)))
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmButton)
                .addGap(29, 29, 29)
                .addComponent(notifyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmButtonMouseClicked
        if(addRadioButton.isSelected())
        {
            if(handRadioButton.isSelected())
            {
                AddWord addFrame = new AddWord();
                addFrame.setVisible(true);
            }
            else
            {
                AddWordByExcel addFromExcelFrame = new AddWordByExcel();
                addFromExcelFrame.setVisible(true);
            }
            notifyLabel.setVisible(false);
        }
        else if(changeRadioButton.isSelected())
        {
            ChangeWord changeWordFrame = new ChangeWord();
            changeWordFrame.setVisible(true);
            notifyLabel.setVisible(false);
        }
        else if(deleteRadioButton.isSelected())
        {
            DeleteWord deleteWordFrame = new DeleteWord();
            deleteWordFrame.setVisible(true);
            notifyLabel.setVisible(false);
        }
        else
        {
            notifyLabel.setText("Chọn 1 hành đông");
            notifyLabel.setBackground(Color.red);
        }
    }//GEN-LAST:event_confirmButtonMouseClicked

    private void addRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRadioButtonMouseClicked
        handRadioButton.setVisible(true);
        excelRadioButton.setVisible(true);
    }//GEN-LAST:event_addRadioButtonMouseClicked

    private void changeRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeRadioButtonMouseClicked
        handRadioButton.setVisible(false);
        excelRadioButton.setVisible(false);
    }//GEN-LAST:event_changeRadioButtonMouseClicked

    private void deleteRadioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteRadioButtonMouseClicked
        handRadioButton.setVisible(false);
        excelRadioButton.setVisible(false);
    }//GEN-LAST:event_deleteRadioButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton addRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JRadioButton changeRadioButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JRadioButton deleteRadioButton;
    private javax.swing.JRadioButton excelRadioButton;
    private javax.swing.JRadioButton handRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel notifyLabel;
    // End of variables declaration//GEN-END:variables
}
